database:
  type: mysql
  host: '127.0.0.1'
  port: '3306'
  database: "hideandseek"
  user: 'user'
  password: 'password'

teleport_to_spawn_on_join: true
spawn_world: "world"

allow_breaking_blocks_outside_arena: true
allow_placing_blocks_outside_arena: true